import { SUPABASE_URL as _SUPABASE_URL, SUPABASE_ANON_KEY as _SUPABASE_ANON_KEY, MAPBOX_ACCESS_TOKEN as _MAPBOX_ACCESS_TOKEN } from '@env';

export const SUPABASE_URL: string = _SUPABASE_URL;
export const SUPABASE_ANON_KEY: string = _SUPABASE_ANON_KEY;
export const MAPBOX_ACCESS_TOKEN: string = _MAPBOX_ACCESS_TOKEN;
